import { auth, db } from "./firebase.js";
import { signInWithEmailAndPassword,onAuthStateChanged,signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { collection,getDocs,addDoc,updateDoc,deleteDoc,doc,getDoc,setDoc,serverTimestamp,query,orderBy } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
let editing=null;const $=id=>document.getElementById(id),money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function isAdmin(uid){const s=await getDoc(doc(db,"admins",uid));return s.exists()&&s.data().active===true}
onAuthStateChanged(auth,async user=>{if(!user)return;if(await isAdmin(user.uid))showPanel();else{await signOut(auth);$("loginMsg").textContent="Esta conta não possui acesso administrativo."}});
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);$("loginMsg").textContent=""}catch(e){$("loginMsg").textContent="E-mail ou senha inválidos."}};$("logout").onclick=()=>signOut(auth).then(()=>location.reload());
async function showPanel(){$("login").classList.add("hide");$("panel").classList.remove("hide");$("logout").classList.remove("hide");await load()}
async function load(){const cfg=await getDoc(doc(db,"settings","store"));if(cfg.exists()){const c=cfg.data();$("storeName").value=c.storeName||"SG Impress 3D";$("whatsapp").value=c.whatsapp||"";$("instagram").value=c.instagram||""}const snap=await getDocs(query(collection(db,"products"),orderBy("createdAt","desc")));const arr=snap.docs.map(d=>({id:d.id,...d.data()}));$("statProducts").textContent=arr.length;$("statAvailable").textContent=arr.filter(x=>x.available!==false).length;$("statCategories").textContent=new Set(arr.map(x=>x.category||"Outros")).size;$("statFeatured").textContent=arr.filter(x=>x.featured).length;$("adminProducts").innerHTML=arr.map(p=>`<div class="admin-product-row"><img src="${esc(p.imageUrl||"")}" onerror="this.style.visibility='hidden'"><div class="admin-product-main"><div class="admin-product-name"><strong>${esc(p.name)}</strong>${p.featured?'<span>Destaque</span>':""}</div><small>${money(p.price)} · ${esc(p.category||"Outros")}${p.material?` · ${esc(p.material)}`:""}</small><div class="admin-status ${p.available!==false?"is-on":"is-off"}">${p.available!==false?"Disponível":"Indisponível"}</div></div><div class="actions"><a href="product.html?id=${p.id}" target="_blank" title="Visualizar">👁️</a><button data-edit="${p.id}" title="Editar">✏️</button><button data-del="${p.id}" title="Excluir">🗑️</button></div></div>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>removeProduct(b.dataset.del))}
$("pimage").oninput=()=>{const u=$("pimage").value.trim();$("previewImg").src=u;$("preview").classList.toggle("hide",!u)};
$("saveProduct").onclick=async()=>{const name=$("pname").value.trim(),price=Number($("pprice").value);if(!name||Number.isNaN(price)||price<0)return alert("Informe nome e preço válidos.");const payload={name,price,category:$("pcat").value.trim()||"Outros",imageUrl:$("pimage").value.trim(),imageUrl2:$("pimage2").value.trim(),imageUrl3:$("pimage3").value.trim(),description:$("pdesc").value.trim(),material:$("pmaterial").value.trim(),size:$("psize").value.trim(),colors:$("pcolors").value.trim(),leadTime:$("pleadtime").value.trim(),customizable:$("pcustomizable").checked,featured:$("pfeatured").checked,available:$("pavailable").checked,updatedAt:serverTimestamp()};try{$("saveProduct").disabled=true;if(editing)await updateDoc(doc(db,"products",editing),payload);else await addDoc(collection(db,"products"),{...payload,createdAt:serverTimestamp()});$("productMsg").textContent="Produto salvo com sucesso!";clear();await load()}catch(e){$("productMsg").textContent=e.message}finally{$("saveProduct").disabled=false}};
async function edit(id){const s=await getDoc(doc(db,"products",id));if(!s.exists())return;const p=s.data();editing=id;$("formTitle").textContent="Editar produto";const vals={pname:p.name||"",pprice:p.price??"",pcat:p.category||"",pimage:p.imageUrl||"",pimage2:p.imageUrl2||"",pimage3:p.imageUrl3||"",pdesc:p.description||"",pmaterial:p.material||"",psize:p.size||"",pcolors:p.colors||"",pleadtime:p.leadTime||""};Object.entries(vals).forEach(([id,v])=>$(id).value=v);$("pcustomizable").checked=!!p.customizable;$("pfeatured").checked=!!p.featured;$("pavailable").checked=p.available!==false;$("previewImg").src=p.imageUrl||"";$("preview").classList.toggle("hide",!p.imageUrl);scrollTo({top:0,behavior:"smooth"})}
async function removeProduct(id){if(confirm("Excluir este produto?")){await deleteDoc(doc(db,"products",id));await load()}}
function clear(){editing=null;$("formTitle").textContent="Novo produto";["pname","pprice","pcat","pimage","pimage2","pimage3","pdesc","pmaterial","psize","pcolors","pleadtime"].forEach(x=>$(x).value="");$("pcustomizable").checked=false;$("pfeatured").checked=false;$("pavailable").checked=true;$("preview").classList.add("hide");$("productMsg").textContent=""}$("clear").onclick=clear;
$("saveConfig").onclick=async()=>{try{await setDoc(doc(db,"settings","store"),{storeName:$("storeName").value.trim()||"SG Impress 3D",whatsapp:$("whatsapp").value.replace(/\D/g,""),instagram:$("instagram").value.trim(),updatedAt:serverTimestamp()},{merge:true});$("configMsg").textContent="Configurações salvas!"}catch(e){$("configMsg").textContent=e.message}};