import { db } from "./firebase.js";
import { doc, getDoc, collection, getDocs, query, where } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const $=id=>document.getElementById(id), money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}), esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const CART_KEY="sgImpress3D_cart";let cart=JSON.parse(localStorage.getItem(CART_KEY)||"[]"),config={storeName:"SG Impress 3D",whatsapp:""},product=null,products=[],detailQty=1;
const params=new URLSearchParams(location.search),id=params.get("id");
const whatsappUrl=msg=>`https://wa.me/${String(config.whatsapp||"").replace(/\D/g,"")}?text=${encodeURIComponent(msg)}`;
async function load(){const [cfg,pdoc,list]=await Promise.all([getDoc(doc(db,"settings","store")),id?getDoc(doc(db,"products",id)):Promise.resolve(null),getDocs(query(collection(db,"products"),where("available","==",true)))]);if(cfg.exists())config={...config,...cfg.data()};products=list.docs.map(d=>({id:d.id,...d.data()}));if(!pdoc||!pdoc.exists()){showNotFound();return}product={id:pdoc.id,...pdoc.data()};if(product.available!==true){showNotFound();return}render()}
function showNotFound(){$("productLoading").classList.add("hide");$("notFound").classList.remove("hide")}
function render(){$("productLoading").classList.add("hide");$("productDetail").classList.remove("hide");$("storeName").textContent=config.storeName;document.title=`${product.name} | ${config.storeName}`;$("productCategory").textContent=product.category||"Produto";$("productCategory").href=`index.html#catalogo`;$("productName").textContent=product.name;$("productPrice").textContent=money(product.price);$("productDescription").textContent=product.description||"";const badges=[];if(product.featured)badges.push('<span class="detail-badge">⭐ Destaque</span>');if(product.customizable)badges.push('<span class="detail-badge">🎨 Personalizável</span>');$("productBadges").innerHTML=badges.join("");setSpec("materialBox","productMaterial",product.material);setSpec("sizeBox","productSize",product.size);setSpec("colorsBox","productColors",product.colors);setSpec("leadTimeBox","productLeadTime",product.leadTime);const imgs=[product.imageUrl,product.imageUrl2,product.imageUrl3].filter(Boolean);$("mainPhoto").src=imgs[0]||"";$("mainPhoto").alt=product.name;$("thumbs").innerHTML=imgs.map((url,i)=>`<button class="product-thumb ${i===0?"active":""}" data-img="${esc(url)}"><img src="${esc(url)}" alt=""></button>`).join("");document.querySelectorAll("[data-img]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".product-thumb").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("mainPhoto").src=b.dataset.img});renderRelated();renderCart();updateCount()}
function setSpec(box,id,value){if(value){$(box).classList.remove("hide");$(id).textContent=value}}
function card(p){return `<article class="product-card"><a class="product-card__image" href="product.html?id=${p.id}">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="${esc(p.name)}">`:"Sem imagem"}</a><div class="product-card__content"><span class="product-card__category">${esc(p.category||"Outros")}</span><a class="product-card__name" href="product.html?id=${p.id}">${esc(p.name)}</a><div class="product-card__bottom"><strong>${money(p.price)}</strong></div></div></article>`}
function renderRelated(){const rel=products.filter(p=>p.id!==product.id&&(p.category||"")===(product.category||"")).slice(0,4);if(rel.length){$("relatedSection").classList.remove("hide");$("relatedProducts").innerHTML=rel.map(card).join("")}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCount()}
function add(id,qty){const i=cart.find(x=>x.id===id);i?i.qty+=qty:cart.push({id,qty});saveCart();renderCart();openCart()}
function updateCount(){$("cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function renderCart(){let total=0;$("cartItems").innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id)|| (product&&product.id===i.id?product:null);if(!p)return"";const sub=Number(p.price)*i.qty;total+=sub;return `<div class="cart-item"><img src="${esc(p.imageUrl||"")}" alt=""><div class="cart-item__info"><strong>${esc(p.name)}</strong><small>${money(p.price)}</small><div class="cart-item__qty"><button data-qty="${p.id}" data-change="-1">−</button><span>${i.qty}</span><button data-qty="${p.id}" data-change="1">+</button></div></div><strong>${money(sub)}</strong></div>`}).join(""):'<div class="cart-empty"><span>🛍️</span><p>Seu carrinho está vazio.</p></div>';$("total").textContent=money(total);document.querySelectorAll("[data-qty]").forEach(b=>b.onclick=()=>{const i=cart.find(x=>x.id===b.dataset.qty);if(!i)return;i.qty+=Number(b.dataset.change);if(i.qty<=0)cart=cart.filter(x=>x.id!==b.dataset.qty);saveCart();renderCart()})}
function openCart(){$("cart").classList.remove("hide");document.body.classList.add("cart-open")};function closeCart(){$("cart").classList.add("hide");document.body.classList.remove("cart-open")}
$("minusQty").onclick=()=>{detailQty=Math.max(1,detailQty-1);$("detailQty").textContent=detailQty};$("plusQty").onclick=()=>{detailQty++;$("detailQty").textContent=detailQty};$("addDetailCart").onclick=()=>add(product.id,detailQty);$("buyNow").onclick=()=>{if(!config.whatsapp)return alert("WhatsApp não configurado.");let msg=`Olá! Tenho interesse neste produto da ${config.storeName}:\n\n*${product.name}*\nQuantidade: ${detailQty}\nValor: ${money(Number(product.price)*detailQty)}`;if(product.customizable)msg+=`\n\nGostaria de conversar sobre a personalização.`;window.open(whatsappUrl(msg),"_blank")};$("cartButton").onclick=()=>{renderCart();openCart()};$("closeCart").onclick=closeCart;$("continueShopping").onclick=closeCart;$("cart").onclick=e=>{if(e.target===$("cart"))closeCart()};$("checkout").onclick=()=>{if(!cart.length)return alert("Carrinho vazio.");if(!config.whatsapp)return alert("WhatsApp não configurado.");let total=0,msg=`Olá! Gostaria de fazer um pedido na ${config.storeName}.\n\n*Nome:* ${$("customer").value.trim()||"Cliente"}\n\n*Pedido:*\n`;cart.forEach(i=>{const p=products.find(x=>x.id===i.id)||(product&&product.id===i.id?product:null);if(!p)return;const sub=Number(p.price)*i.qty;total+=sub;msg+=`• ${i.qty}x ${p.name} — ${money(sub)}\n`});msg+=`\n*Total: ${money(total)}*`;const note=$("note").value.trim();if(note)msg+=`\n\n*Observação:* ${note}`;window.open(whatsappUrl(msg),"_blank")};load().catch(e=>{console.error(e);showNotFound()});